language: smalltalk
sudo: true

matrix:
  include:
  - os: linux
    dist: bionic
  - os: linux
    dist: xenial
    
    
before_install:
  - sudo apt-get install libstdc++6
  - sudo apt-get install gcc-6 g++-6 -y
  
  
os:
  - linux
  - windows
  #- osx

smalltalk:
  - Squeak64-5.2
