language: smalltalk
sudo: true

before_install:
  - chmod -R 777 $TRAVIS_BUILD_DIR/build-support/*.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $TRAVIS_BUILD_DIR/build-support/installHunspellOnLinux.sh; fi
  - $TRAVIS_BUILD_DIR/build-support/copydictionaries.sh

os:
  - linux
  - osx

smalltalk:
  - Squeak-5.1
  - Squeak-5.0
