language: smalltalk
sudo: true

matrix:
  include:
  - os: linux
    dist: bionic
  - os: linux
    dist: xenial
before_install:
  - sudo apt install libstdc++6
os:
  - linux
  - windows
  #- osx

smalltalk:
  - Squeak64-5.2
