language: smalltalk
sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libhunspell-1.3-0:i386          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ln -s /usr/lib/i386-linux-gnu/libhunspell-1.3.so.0 libhunspell-1.3.so.0 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls -la ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pwd ; fi

  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install -v hunspell          ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O https://datapacket.dl.sourceforge.net/project/wordlist/speller/2017.01.22/hunspell-en_US-2017.01.22.zip          ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unzip -v hunspell-en_US-2017.01.22.zip          ; fi 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then hunspell -D ; fi
  
  - mkdir -p ../../../smalltalkCI-master/_builds/
  - cp ./packages/dictionaries/en_US.aff ../../../smalltalkCI-master/_builds/en_US.aff
  - cp ./packages/dictionaries/en_US.dic ../../../smalltalkCI-master/_builds/en_US.dic
  - cp ./packages/dictionaries/en_US.aff ../../../smalltalkCI-master/en_US.aff
  - cp ./packages/dictionaries/en_US.dic ../../../smalltalkCI-master/en_US.dic
  - cp ./packages/dictionaries/en_US.aff ../../../en_US.aff
  - cp ./packages/dictionaries/en_US.dic ../../../en_US.dic
  - cp ./packages/dictionaries/en_US.aff ../../en_US.aff
  - cp ./packages/dictionaries/en_US.dic ../../en_US.dic
  - cp ./packages/dictionaries/en_US.aff ../en_US.aff
  - cp ./packages/dictionaries/en_US.dic ../en_US.dic
  - ls -la  ../../../smalltalkCI-master/_builds/
  - ls -la  ../../../smalltalkCI-master/
  - ls -la  ../../../
  - ls -la  ../../
  - ls -la  ../
  

os:
  - linux
  - osx

smalltalk:
  - Squeak-5.1
  - Squeak-5.0
