language: smalltalk
sudo: true

before_install:
  - chmod -R 777 $TRAVIS_BUILD_DIR/build-support/*.sh
  - $TRAVIS_BUILD_DIR/build-support/copydictionaries.sh

os:
  - linux
  - osx

smalltalk:
  - Squeak-5.1
  - Squeak-5.0
