language: smalltalk
sudo: true

matrix:
  include:
  - os: linux
    dist: bionic
  - os: linux
    dist: xenial
    
    
before_install:
  - echo "Installing lib."
  - chmod -R 777 $TRAVIS_BUILD_DIR/build-support/*.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $TRAVIS_BUILD_DIR/build-support/installHunspellOnLinux.sh; fi
  - $TRAVIS_BUILD_DIR/build-support/copydictionaries.sh
  
  
os:
  - linux
  - windows
  #- osx

smalltalk:
  - Squeak64-5.2
