language: smalltalk
sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ldd hunspell.so ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nm -D hunspell.so ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ls -la ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pwd ; fi

  - ls -la
  

os:
  - linux
  - osx

smalltalk:
  - Squeak-5.1
  - Squeak-5.0
