language: smalltalk
sudo: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls -la ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pwd ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ldd hunspell.so ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nm -D hunspell.so  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libhunspell-1.3-0:i386          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ln -s /usr/lib/i386-linux-gnu/libhunspell-1.3.so.0 libhunspell-1.3.so.0 ; fi
  - chmod -R 777 $TRAVIS_BUILD_DIR/build-support/*.sh
  - $TRAVIS_BUILD_DIR/build-support/copydictionaries.sh

os:
  - linux
  - osx

smalltalk:
  - Squeak-5.1
  - Squeak-5.0
