#language: smalltalk
#sudo: true

matrix:
  include:
    - language: smalltalk
    os: linux
    dist: bionic

before_install:
  - echo "Installing lib."
  - chmod -R 777 $TRAVIS_BUILD_DIR/build-support/*.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $TRAVIS_BUILD_DIR/build-support/installHunspellOnLinux.sh; fi
  - $TRAVIS_BUILD_DIR/build-support/copydictionaries.sh

os:
  - linux
  #- osx

smalltalk:
  - Squeak32-5.2
