language: smalltalk
sudo: true

matrix:
  include:
  - os: linux
    dist: bionic
  - os: linux
    dist: xenial
    
    
before_install:
  - sudo apt-get install libstdc++6
  - sudo apt-get install gcc g++ -y
  - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH
  
  
os:
  - linux
  - windows
  #- osx

smalltalk:
  - Squeak64-5.2
